# Generated by Django 4.2.6 on 2023-10-23 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criticy',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Criticy'),
        ),
        migrations.AlterField(
            model_name='criticy',
            name='level',
            field=models.CharField(max_length=255, verbose_name='Level Criticy'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Especialidad'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Especialidad'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Tech'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nombre Tech'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Ticket'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Titulo Ticket'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha creación Ticket History'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Ticket History'),
        ),
    ]
