# Generated by Django 4.2.6 on 2023-10-23 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_criticy_id_alter_criticy_level_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickethistory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tickethistory',
            name='entry',
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de registro en el historial'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tickethistory',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción del cambio'),
        ),
    ]
