# Generated by Django 4.2.5 on 2023-10-24 14:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_tickethistory_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID Status')),
                ('stado', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='speciality',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre Especialidad'),
        ),
        migrations.AlterField(
            model_name='tech',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='tech',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nombre Tech'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='Abierto', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='core.status'),
        ),
    ]
