# Generated by Django 4.2.5 on 2023-10-24 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_stado_status_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='history',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket', to='core.tickethistory'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tech',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.tech'),
        ),
    ]
